import { jsPDF } from 'jspdf';

/**
 * Truncates text cleanly with an ellipsis (…) if it exceeds maxWidth in millimeters
 */
function fitText(doc, text, maxWidth) {
  if (!text) return '';
  let str = String(text);
  if (doc.getTextWidth(str) <= maxWidth) return str;
  while (str.length > 1 && doc.getTextWidth(str + '…') > maxWidth) {
    str = str.slice(0, -1);
  }
  return str + '…';
}

/**
 * Normalizes and formats date strings cleanly for reports
 */
function formatDateStr(dateVal) {
  if (!dateVal || dateVal === 'all time') return 'All Time';
  try {
    const d = new Date(dateVal);
    if (isNaN(d.getTime())) return String(dateVal).slice(0, 10);
    return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  } catch {
    return String(dateVal).slice(0, 10);
  }
}

/**
 * Generates and downloads an official high-resolution EventHub Business Intelligence & Audit Report PDF
 * with guaranteed mathematical boundary checks, zero text clipping/overlap, and dynamic multi-page ledger support.
 * 
 * @param {Object} options
 * @param {string} options.reportType - 'bookings' | 'events'
 * @param {Object} options.reportData - The generated report payload from MongoDB
 * @param {Object} options.adminUser - The currently logged-in Admin or Organizer user details
 */
export const downloadReportPdf = ({ reportType, reportData, adminUser }) => {
  if (!reportData) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4', // 210 x 297 mm
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 14;
  const contentWidth = pageWidth - margin * 2; // 182 mm

  // 1. Header Accent Banner
  doc.setFillColor(79, 70, 229); // Indigo-600
  doc.rect(0, 0, pageWidth, 5, 'F');

  // 2. Platform Branding & Title Container
  doc.setFillColor(15, 23, 42); // Slate-900
  doc.roundedRect(margin, 12, contentWidth, 24, 3, 3, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('EventHub', margin + 8, 23);

  doc.setFontSize(8.5);
  doc.setTextColor(165, 180, 252); // Indigo-300
  const subTitle = adminUser?.role === 'ORGANIZER'
    ? 'ORGANIZER REVENUE & TICKET SALES AUDIT'
    : 'EXECUTIVE AUDIT & BUSINESS INTELLIGENCE REPORT';
  doc.text(fitText(doc, subTitle, 105), margin + 8, 30);

  // Right-aligned status badge
  doc.setFillColor(16, 185, 129); // Emerald-500
  doc.roundedRect(pageWidth - margin - 38, 18, 30, 6.5, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.text('VERIFIED AUDIT', pageWidth - margin - 23, 22.3, { align: 'center' });

  // 3. Metadata Information Panel (2-column layout with strict boundaries)
  let currentY = 41;
  doc.setFillColor(248, 250, 252); // Slate-50
  doc.roundedRect(margin, currentY, contentWidth, 23, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240); // Slate-200
  doc.roundedRect(margin, currentY, contentWidth, 23, 2, 2, 'S');

  // Column 1 (Left)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text('REPORT TYPE:', margin + 6, currentY + 7);
  doc.text('REPORT ID:', margin + 6, currentY + 15);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  const typeLabel = reportType === 'bookings' ? 'Booking Transactions & Revenue' : 'Event Capacity & Performance';
  doc.text(fitText(doc, typeLabel, 54), margin + 30, currentY + 7);
  doc.text(fitText(doc, reportData.reportId || 'GEN-REP-AUDIT', 54), margin + 30, currentY + 15);

  // Column 2 (Right)
  const actorLabel = adminUser?.role === 'ORGANIZER' ? 'ORGANIZER:' : 'GENERATED BY:';
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text(actorLabel, margin + 96, currentY + 7);
  doc.text('DATE RANGE:', margin + 96, currentY + 15);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(15, 23, 42);
  const actorName = adminUser?.name || (adminUser?.role === 'ORGANIZER' ? 'Organizer' : 'Administrator');
  doc.text(fitText(doc, actorName, 56), margin + 124, currentY + 7);

  const rangeStart = reportData.dateRange?.startDate || reportData.filter?.startDate || 'All Time';
  const rangeEnd = reportData.dateRange?.endDate || reportData.filter?.endDate || 'All Time';
  const rangeText = `${formatDateStr(rangeStart)} to ${formatDateStr(rangeEnd)}`;
  doc.text(fitText(doc, rangeText, 56), margin + 124, currentY + 15);

  // 4. Executive KPI Cards (Exact 3 Cards)
  currentY += 28;
  const hasRefunds = (reportData.totalRefunded || 0) > 0;
  const numCards = hasRefunds ? 4 : 3;
  const cardWidth = (contentWidth - (numCards - 1) * 3) / numCards;
  const cardHeight = 18;

  const totalRecords = reportData.totalBookings ?? reportData.totalEvents ?? 0;
  const confirmedTickets = reportData.totalTicketsConfirmed ?? 0;
  const revenue = reportData.totalRevenue || 0;
  const refunded = reportData.totalRefunded || 0;

  const kpis = [
    { label: 'TOTAL RECORDS', val: `${totalRecords}` },
    { 
      label: reportType === 'bookings' ? 'CONFIRMED PASSES' : 'CAPACITY / SOLD', 
      val: reportType === 'bookings' 
        ? `${confirmedTickets}` 
        : `${reportData.events?.reduce((acc, ev) => acc + (ev.ticketsSold || 0), 0) || 0} Sold`
    },
    { label: hasRefunds ? 'NET REVENUE' : 'GROSS REVENUE', val: `INR ${revenue.toLocaleString('en-IN')}` },
  ];

  if (hasRefunds) {
    kpis.push({ label: 'TOTAL REFUNDED', val: `INR ${refunded.toLocaleString('en-IN')}` });
  }

  kpis.forEach((kpi, idx) => {
    const kpiX = margin + idx * (cardWidth + 3);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(kpiX, currentY, cardWidth, cardHeight, 2, 2, 'F');
    doc.setDrawColor(203, 213, 225);
    doc.roundedRect(kpiX, currentY, cardWidth, cardHeight, 2, 2, 'S');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(kpi.label, kpiX + 4, currentY + 6);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(doc.getTextWidth(kpi.val) > cardWidth - 8 ? 8.5 : 10);
    doc.setTextColor(15, 23, 42);
    doc.text(kpi.val, kpiX + 4, currentY + 13.5);
  });

  // 5. Itemized Table Section
  currentY += 25;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.text(
    reportType === 'bookings' ? 'Itemized Booking Transactions Ledger' : 'Event Inventory & Performance Summary',
    margin,
    currentY
  );

  currentY += 4;

  const drawTableHeader = (y) => {
    doc.setFillColor(30, 41, 59);
    doc.rect(margin, y, contentWidth, 7, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');

    if (reportType === 'bookings') {
      doc.text('# REF', margin + 4, y + 4.8);
      doc.text('ATTENDEE', margin + 26, y + 4.8);
      doc.text('EVENT NAME', margin + 68, y + 4.8);
      doc.text('STATUS', margin + 128, y + 4.8, { align: 'center' });
      doc.text('QTY', margin + 152, y + 4.8, { align: 'center' });
      doc.text('AMOUNT', margin + contentWidth - 4, y + 4.8, { align: 'right' });
    } else {
      doc.text('EVENT NAME', margin + 4, y + 4.8);
      doc.text('HOST ORGANIZER', margin + 66, y + 4.8);
      doc.text('STATUS', margin + 122, y + 4.8, { align: 'center' });
      doc.text('SOLD / CAP', margin + 148, y + 4.8, { align: 'center' });
      doc.text('REVENUE', margin + contentWidth - 4, y + 4.8, { align: 'right' });
    }
  };

  drawTableHeader(currentY);
  currentY += 7;

  if (reportType === 'bookings') {
    const bookings = reportData.bookings || [];

    if (bookings.length === 0) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text('No booking transactions found for the specified period.', margin + 4, currentY + 6);
      currentY += 10;
    } else {
      bookings.forEach((b, i) => {
        // Multi-page check
        if (currentY + 7 > 274) {
          doc.addPage();
          doc.setFillColor(79, 70, 229);
          doc.rect(0, 0, pageWidth, 4, 'F');

          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(100, 116, 139);
          doc.text('EventHub Audit Ledger · Continued', margin, 12);

          currentY = 16;
          drawTableHeader(currentY);
          currentY += 7;
        }

        if (i % 2 === 0) {
          doc.setFillColor(248, 250, 252);
          doc.rect(margin, currentY, contentWidth, 6.5, 'F');
        }

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(15, 23, 42);

        const ref = `#BKG-${(b._id || '').slice(-6).toUpperCase()}`;
        const attendeeName = fitText(doc, b.user?.name || 'Customer', 38);
        const evName = fitText(doc, b.event?.eventName || 'Live Event', 44);
        const bStatus = b.bookingStatus || 'CONFIRMED';
        const qty = `${b.ticketCount || 1}`;
        const amt = `INR ${(b.totalAmount || (b.event?.ticketPrice || 0) * (b.ticketCount || 1)).toLocaleString('en-IN')}`;

        doc.text(ref, margin + 4, currentY + 4.4);
        doc.text(attendeeName, margin + 26, currentY + 4.4);
        doc.text(evName, margin + 68, currentY + 4.4);

        // Status pill
        if (bStatus === 'CONFIRMED') doc.setTextColor(16, 185, 129);
        else if (bStatus === 'CANCELLED' || bStatus === 'PAYMENT_FAILED') doc.setTextColor(239, 68, 68);
        else doc.setTextColor(245, 158, 11);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(bStatus === 'PAYMENT_FAILED' ? 5.8 : 6.5);
        doc.text(bStatus, margin + 128, currentY + 4.4, { align: 'center' });

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(15, 23, 42);
        doc.text(qty, margin + 152, currentY + 4.4, { align: 'center' });
        doc.text(amt, margin + contentWidth - 4, currentY + 4.4, { align: 'right' });

        currentY += 6.5;
      });

      // Table summary row
      if (currentY + 8 > 274) {
        doc.addPage();
        currentY = 16;
      }

      doc.setFillColor(241, 245, 249);
      doc.rect(margin, currentY, contentWidth, 7, 'F');
      doc.setDrawColor(203, 213, 225);
      doc.line(margin, currentY, margin + contentWidth, currentY);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(15, 23, 42);
      doc.text(`Total Summary (${bookings.length} Transactions)`, margin + 4, currentY + 4.8);
      doc.text(`${reportData.totalTicketsConfirmed ?? 0}`, margin + 152, currentY + 4.8, { align: 'center' });
      doc.setTextColor(16, 185, 129);
      doc.text(`INR ${(reportData.totalRevenue || 0).toLocaleString('en-IN')}`, margin + contentWidth - 4, currentY + 4.8, { align: 'right' });
    }
  } else {
    // Events table
    const events = reportData.events || [];

    if (events.length === 0) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text('No event records found for the specified period.', margin + 4, currentY + 6);
      currentY += 10;
    } else {
      events.forEach((e, i) => {
        // Multi-page check
        if (currentY + 7 > 274) {
          doc.addPage();
          doc.setFillColor(79, 70, 229);
          doc.rect(0, 0, pageWidth, 4, 'F');

          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(100, 116, 139);
          doc.text('EventHub Audit Ledger · Continued', margin, 12);

          currentY = 16;
          drawTableHeader(currentY);
          currentY += 7;
        }

        if (i % 2 === 0) {
          doc.setFillColor(248, 250, 252);
          doc.rect(margin, currentY, contentWidth, 6.5, 'F');
        }

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(15, 23, 42);

        const evName = fitText(doc, e.eventName || 'Event Experience', 46);
        const orgName = fitText(doc, e.organizer?.name || 'Organizer', 38);
        const evStatus = e.status || 'ACTIVE';
        const capRatio = `${e.ticketsSold || 0} / ${e.totalCapacity || e.seatsRemaining || 0}`;
        const evRev = `INR ${(e.revenue || 0).toLocaleString('en-IN')}`;

        doc.text(evName, margin + 4, currentY + 4.4);
        doc.text(orgName, margin + 66, currentY + 4.4);

        if (evStatus === 'ACTIVE') doc.setTextColor(16, 185, 129);
        else if (evStatus === 'CANCELLED') doc.setTextColor(239, 68, 68);
        else doc.setTextColor(99, 102, 241);

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6.5);
        doc.text(evStatus, margin + 122, currentY + 4.4, { align: 'center' });

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(15, 23, 42);
        doc.text(capRatio, margin + 148, currentY + 4.4, { align: 'center' });
        doc.text(evRev, margin + contentWidth - 4, currentY + 4.4, { align: 'right' });

        currentY += 6.5;
      });

      // Table summary row
      if (currentY + 8 > 274) {
        doc.addPage();
        currentY = 16;
      }

      doc.setFillColor(241, 245, 249);
      doc.rect(margin, currentY, contentWidth, 7, 'F');
      doc.setDrawColor(203, 213, 225);
      doc.line(margin, currentY, margin + contentWidth, currentY);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(15, 23, 42);
      doc.text(`Total Capacity Summary (${events.length} Events)`, margin + 4, currentY + 4.8);
      const totalSold = events.reduce((acc, ev) => acc + (ev.ticketsSold || 0), 0);
      doc.text(`${totalSold} Sold`, margin + 148, currentY + 4.8, { align: 'center' });
      doc.setTextColor(16, 185, 129);
      const totalEvRev = events.reduce((acc, ev) => acc + (ev.revenue || 0), 0);
      doc.text(`INR ${totalEvRev.toLocaleString('en-IN')}`, margin + contentWidth - 4, currentY + 4.8, { align: 'right' });
    }
  }

  // 6. Running Footer with total page count on ALL pages
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(
      `Official EventHub Management System Audit Ledger | Confidential Enterprise Document | Page ${p} of ${totalPages}`,
      pageWidth / 2,
      288,
      { align: 'center' }
    );
  }

  // 7. Save and trigger download
  const dateStamp = new Date().toISOString().slice(0, 10);
  const filename = `EventHub_${reportType === 'bookings' ? 'Booking_Audit' : 'Event_Report'}_${dateStamp}.pdf`;
  if (typeof doc.save === 'function') {
    doc.save(filename);
  }
  return { doc, filename };
};
